In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from sklearn.datasets import load_iris

In [3]:
iris_obj =load_iris()
iris_obj.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
iris_obj.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris_obj.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris_obj.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
iris = DataFrame(iris_obj.data, columns=iris_obj.feature_names,
                index = pd.index([i for i in range(iris_obj.data.shape[0])])
                join(DataFrame(iris_obj.target, column=pd.index(['species']), index=pd.index([i for i in range(iris_obj.target.shape)])))

SyntaxError: invalid syntax (<ipython-input-6-1ac047f138e9>, line 3)

In [156]:
iris = DataFrame(iris_obj.data, columns= iris_obj.feature_names)

In [157]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [158]:
iris['Species'] = iris_obj.target

In [159]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0

In [11]:
iris.Species.replace({0:'Setosa', 1:'Versicolor', 2:'Virginicia'}, inplace=True)

In [12]:
iris_obj.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
iris_obj.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

In [15]:
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  Species  
0  Setosa  
1  Setosa  
2  Setosa  
3  Setosa  
4  Setosa

In [16]:
# Descriptive statistics to be done in groups
iris_grps = iris.groupby("Species")

In [17]:
iris_grps

In [18]:
for name, data in iris_grps:
    print(name)
    print("............/n/n")
    print(data.iloc[:, 0:4])
    print("/n/n/n/n")

Setosa
............/n/n
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4             

In [19]:
iris.count()

sepal length (cm)    150
sepal width (cm)     150
petal length (cm)    150
petal width (cm)     150
Species              150
dtype: int64

In [20]:
iris.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [21]:
iris.median()

sepal length (cm)    5.80
sepal width (cm)     3.00
petal length (cm)    4.35
petal width (cm)     1.30
dtype: float64

In [22]:
iris.mode()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.0               3.0                1.4               0.2   
1                NaN               NaN                1.5               NaN   
2                NaN               NaN                NaN               NaN   

      Species  
0      Setosa  
1  Versicolor  
2  Virginicia

In [23]:
iris.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [24]:
iris.std()

sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64

In [25]:
iris.quantile(.1)

sepal length (cm)    4.8
sepal width (cm)     2.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0.1, dtype: float64

In [26]:
iris.quantile(.95)

sepal length (cm)    7.255
sepal width (cm)     3.800
petal length (cm)    6.100
petal width (cm)     2.300
Name: 0.95, dtype: float64

In [27]:
iris.quantile(.75)

sepal length (cm)    6.4
sepal width (cm)     3.3
petal length (cm)    5.1
petal width (cm)     1.8
Name: 0.75, dtype: float64

In [28]:
iris.quantile(.25)

sepal length (cm)    5.1
sepal width (cm)     2.8
petal length (cm)    1.6
petal width (cm)     0.3
Name: 0.25, dtype: float64

In [29]:
interquantile_range = iris.quantile(.75) - iris.quantile(.25)
interquantile_range

sepal length (cm)    1.3
sepal width (cm)     0.5
petal length (cm)    3.5
petal width (cm)     1.5
dtype: float64

In [30]:
iris.max()

sepal length (cm)           7.9
sepal width (cm)            4.4
petal length (cm)           6.9
petal width (cm)            2.5
Species              Virginicia
dtype: object

In [31]:
iris.min()

sepal length (cm)       4.3
sepal width (cm)          2
petal length (cm)         1
petal width (cm)        0.1
Species              Setosa
dtype: object

In [32]:
iris_grps.mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Species                                                              
Setosa                  5.006             3.428              1.462   
Versicolor              5.936             2.770              4.260   
Virginicia              6.588             2.974              5.552   

            petal width (cm)  
Species                       
Setosa                 0.246  
Versicolor             1.326  
Virginicia             2.026

In [33]:
iris_grps.mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Species                                                              
Setosa                  5.006             3.428              1.462   
Versicolor              5.936             2.770              4.260   
Virginicia              6.588             2.974              5.552   

            petal width (cm)  
Species                       
Setosa                 0.246  
Versicolor             1.326  
Virginicia             2.026

In [34]:
iris_grps.std()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Species                                                              
Setosa               0.352490          0.379064           0.173664   
Versicolor           0.516171          0.313798           0.469911   
Virginicia           0.635880          0.322497           0.551895   

            petal width (cm)  
Species                       
Setosa              0.105386  
Versicolor          0.197753  
Virginicia          0.274650

In [35]:
iris_grps.quantile(.25)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Species                                                              
Setosa                  4.800             3.200                1.4   
Versicolor              5.600             2.525                4.0   
Virginicia              6.225             2.800                5.1   

            petal width (cm)  
Species                       
Setosa                   0.2  
Versicolor               1.2  
Virginicia               1.8

In [36]:
iris.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [37]:
iris_grps.describe()

sepal length (cm)                                              \
                       count   mean       std  min    25%  50%  75%  max   
Species                                                                    
Setosa                  50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8   
Versicolor              50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0   
Virginicia              50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9   

           sepal width (cm)         ... petal length (cm)       \
                      count   mean  ...               75%  max   
Species                             ...                          
Setosa                 50.0  3.428  ...             1.575  1.9   
Versicolor             50.0  2.770  ...             4.600  5.1   
Virginicia             50.0  2.974  ...             5.875  6.9   

           petal width (cm)                                            
                      count   mean       std  min  25%  50%  75%  max  
Species                                                                
Setosa                 50.0  0.246  0.105386  0.1  0.2  0.2  0.3  0.6  
Versicolor             50.0  1.326  0.197753  1.0  1.2  1.3  1.5  1.8  
Virginicia             50.0  2.026  0.274650  1.4  1.8  2.0  2.3  2.5  

[3 rows x 32 columns]

In [38]:
def range_stat(s):
    return s.max() - s.min()
iris.iloc[:, 0:4].apply(range_stat)

sepal length (cm)    3.6
sepal width (cm)     2.4
petal length (cm)    5.9
petal width (cm)     2.4
dtype: float64

In [39]:
iris.iloc[:, 0:4].apply(range_stat)

sepal length (cm)    3.6
sepal width (cm)     2.4
petal length (cm)    5.9
petal width (cm)     2.4
dtype: float64

In [40]:
iris_grps.aggregate(range_stat)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
Species                                                              
Setosa                    1.5               2.1                0.9   
Versicolor                2.1               1.4                2.1   
Virginicia                3.0               1.6                2.4   

            petal width (cm)  
Species                       
Setosa                   0.5  
Versicolor               0.8  
Virginicia               1.1

## Machine learning

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

## Logistic Regression

In [42]:
x = iris[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']]

In [43]:
y = iris['Species']

In [44]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

In [45]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=89)

In [139]:
model = LogisticRegression()

In [140]:
model.fit(X_train, y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/root/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [141]:
y_pred = model.predict(X_test)

In [142]:
print(accuracy_score(y_test, y_pred))

0.9210526315789473


In [143]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        12
  Versicolor       1.00      0.79      0.88        14
  Virginicia       0.80      1.00      0.89        12

    accuracy                           0.92        38
   macro avg       0.93      0.93      0.92        38
weighted avg       0.94      0.92      0.92        38



In [144]:
print(confusion_matrix(y_test, y_pred))

[[12  0  0]
 [ 0 11  3]
 [ 0  0 12]]


In [135]:
print(confusion_matrix(y_pred, y_test))

[[19  0  0]
 [ 0 10  1]
 [ 0  0 15]]


In [53]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       0.70      0.78      0.74         9
  Virginicia       0.88      0.82      0.85        17

    accuracy                           0.89        45
   macro avg       0.86      0.87      0.86        45
weighted avg       0.89      0.89      0.89        45



### Decision Trees

In [54]:
tree = DecisionTreeClassifier()

In [55]:
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [56]:
tree_pred = tree.predict(X_test)

In [57]:
print(classification_report(y_test, tree_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       0.90      0.90      0.90        10
  Virginicia       0.94      0.94      0.94        16

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [137]:
print(confusion_matrix(y_test, tree_pred))

[[19  0  0]
 [ 0  9  1]
 [ 0  1 15]]


In [136]:
accuracy_score(y_test, tree_pred)

0.9555555555555556

## Random Forest

In [60]:
rf_model = RandomForestClassifier()

In [61]:
rf_model.fit(X_train, y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [62]:
rf_pred = rf_model.predict(X_test)

In [63]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       0.83      1.00      0.91        10
  Virginicia       1.00      0.88      0.93        16

    accuracy                           0.96        45
   macro avg       0.94      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [64]:
print(confusion_matrix(y_test, rf_pred))

[[19  0  0]
 [ 0 10  0]
 [ 0  2 14]]


In [65]:
print("the accuracy of the model is:", accuracy_score(y_test, rf_pred))

the accuracy of the model is: 0.9555555555555556


## KNN

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
knn = KNeighborsClassifier()

In [68]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [71]:
print(confusion_matrix(y_test, knn_pred))

[[19  0  0]
 [ 0 10  0]
 [ 0  1 15]]


In [70]:
knn_pred  = knn.predict(X_test)

In [72]:
print(accuracy_score(y_test, knn_pred))

0.9777777777777777


## Naive Bayes

In [73]:
naive_bayes = GaussianNB()

In [74]:
naive_bayes.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [75]:
naive_pred = naive_bayes.predict(X_test)

In [131]:
accuracy_score(y_test, naive_pred)

0.9777777777777777

In [77]:
print(classification_report(y_test, naive_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       0.91      1.00      0.95        10
  Virginicia       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [78]:
print(confusion_matrix(y_test, naive_pred))

[[19  0  0]
 [ 0 10  0]
 [ 0  1 15]]


In [79]:
predictions = pd.DataFrame(y_test, naive_pred)

In [80]:
predictions.head()


Species
Virginicia     NaN
Virginicia     NaN
Setosa         NaN
Setosa         NaN
Virginicia     NaN

In [81]:
import matplotlib.pyplot as plt
plt.scatter('y_test', 'naive_pred')
plt.show()

<Figure size 640x480 with 1 Axes>

## PCA

In [82]:
from sklearn.decomposition import PCA
from itertools import cycle

In [83]:
pca = PCA(n_components = 2, whiten=True)

In [84]:
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=True)

In [85]:
pca.components_

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [ 0.65658877,  0.73016143, -0.17337266, -0.07548102]])

In [86]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648])

In [87]:
x_pca = pca.transform(x)

In [88]:
x_pca.shape

(150, 2)

In [89]:
x.shape

(150, 4)

In [90]:
from sklearn.datasets import load_iris

In [91]:
iris_obj = load_iris()

In [92]:
data = iris_obj.data
target = iris_obj.target

def plot_iris(data, target, target_names):
    colors = cycle('rgb')
    ids = range(len(target_names))
    plt.figure()
    
    for x, c , label in zip(ids, colors, target_names):
        plt.scatter(data[target == x , 0], data[target == x, 1], c=c, label=label)
    plt.legend()
plot_iris(x_pca, iris.target, iris.target_names)
        

## KFold and SVM

In [94]:
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV

In [95]:
from sklearn.svm import SVC

In [98]:
clf = SVC(kernel='linear', C=1, degree=3).fit(X_train, y_train)

In [100]:
clf.score(X_train, y_train)

0.9809523809523809

In [101]:
score = cross_val_score(clf, x, y, cv=5)

In [102]:
score

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [103]:
score.mean()

0.9800000000000001

In [108]:
clf2 = SVC(kernel='poly',C=2, degree=2).fit(X_train, y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [109]:
clf2.fit(X_train, y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [122]:
score2 = cross_val_score(clf2, x, y, cv=2)

/root/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/root/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [123]:
score

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [124]:
score.mean()

0.9800000000000001

In [117]:
svm = SVC()

In [118]:
svm.fit(X_train, y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [119]:
y_pred = svm.predict(X_test)

In [120]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        19
  Versicolor       0.91      1.00      0.95        10
  Virginicia       1.00      0.94      0.97        16

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [121]:
print(confusion_matrix(y_test, y_pred))

[[19  0  0]
 [ 0 10  0]
 [ 0  1 15]]


## GridSearchCV

In [160]:
x = iris[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']]
y = iris.Species

In [155]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [172]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=5)

In [173]:
model = LogisticRegression()

In [174]:
model.fit(X_train,y_train)

/root/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/root/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [175]:
log_pred = model.predict(X_test)

In [176]:
accuracy_score(y_test, log_pred)

0.9333333333333333

In [177]:
kvalue_range = len(range(1,30))
scores = []

In [180]:
for kvalue in kvalue_range:
    knn = KNeighborsClassifier(n_neighbors=kvalue_range)
    knn.fit(X_train, y_train)
    knn_pred = knn.predict(X_test)
    scores.append(accuracy_score(y_test, knn_pred))
print(scores)

TypeError: 'int' object is not iterable

In [181]:
for kvalue in kvalue_range:
    knn = KNeighborsClassifier(n_neighbors = kvalue)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append(accuracy_score(y_test, y_pred))
    
print(scores)

TypeError: 'int' object is not iterable

In [4]:
pip install pytorch

  ERROR: Command errored out with exit status 1:
   command: /root/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x0tiarok/pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x0tiarok/pytorch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-icox77fi --python-tag cp37
       cwd: /tmp/pip-install-x0tiarok/pytorch/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-x0tiarok/pytorch/setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
  ----------------------------------------
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
  Running setup.py install fo